server:
  port: 8080

spring:
  application:
    name: zxl-consumer-depart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8888
      # 该配置能够使dashboard主动发现该应用
      eager: true
#      datasource:
#        flow:
#          file:
#            file: classpath:flowrule.json
#            data-type: json
#            rule-type: flow
      datasource:
        flow:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: DEFAULT_GROUP
            rule-type: flow